.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- Bug report template
- Feature request template
=> Add GitHub templates

packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-types/src/index.ts, packages/safe-core-sdk-types/src/types.ts, packages/safe-core-sdk-types/tsconfig.json
Extract common types from `packages/safe-core-sdk` to `packages/safe-core-sdk-types`
=> Add Safe Core SDK types

packages/safe-core-sdk-types/package.json
=> Update Safe Core SDK Types

.github/workflows/typedoc.yml
After merging #83, it turned out the build isn't working in the typedoc action.
This PR is to debug and fix that.
=> Fix the typedoc action

packages/safe-service-client/package.json, yarn.lock
`node-fetch` dependency is missing.
This PR add it to the `package.json` file.
=> Add node-fetch dependency

packages/guides/README.md, packages/guides/integrating-the-safe-core-sdk.md
Creation of a guide that shows the basic steps for interacting with the `Safe Core SDK` and `Safe Service Client` libraries
=> SDK's guide

packages/safe-ethers-adapters/package.json, yarn.lock
Just rebuilt & republished to fix imports
=> safe-ethers-adapters v0.1.0-alpha.5

packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryContract.ts, packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryEthersContract.ts, packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts, packages/safe-core-sdk/src/safeFactory/index.ts
=> Remove createProxy without nonce

packages/safe-ethers-adapters/package.json
=> 0.1.0 alpha.7 Safe ethers adapters 

packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts
=> Fix retrieval of ProxyCreation event

packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryEthersContract.ts, packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts, packages/safe-core-sdk/tests/safeFactory.test.ts
=> Throw error if saltNonce is a negative integer

packages/guides/integrating-the-safe-core-sdk.md, packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/src/SafeTransactionService.ts, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts, packages/safe-service-client/tests/endpoint.test.ts
=> Add `origin` property to `proposeTransaction()`

packages/guides/integrating-the-safe-core-sdk.md, packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-utils/package.json, packages/safe-core-sdk/README.md, packages/safe-core-sdk/package.json, packages/safe-ethers-adapters/package.json, packages/safe-ethers-lib/package.json, packages/safe-service-client/package.json, packages/safe-web3-lib/package.json, yarn.lock
=> Update package versions

packages/safe-core-sdk/README.md
Fixes broken link to docs about sending transactions
=> Fix broken transaction docs link

packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-utils/package.json, packages/safe-core-sdk-utils/src/eip-3770/config.ts, packages/safe-core-sdk/package.json, packages/safe-ethers-adapters/package.json, yarn.lock
Resolves https://github.com/safe-global/safe-core-sdk/issues/218
=> Update safe-deployments to v1.15.0

packages/safe-service-client/README.md, packages/safe-service-client/package.json, packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts, packages/safe-service-client/tests/e2e/getSafesByModule.test.ts, packages/safe-service-client/tests/endpoint/index.test.ts, yarn.lock
=> Support endpoint to get all the Safes with a given module enabled

packages/safe-core-sdk-utils/tests/eip-3770.test.ts, packages/safe-core-sdk/hardhat.config.ts, packages/safe-ethers-adapters/.env.sample, packages/safe-service-client/hardhat.config.ts, packages/safe-service-client/scripts/generateTxServiceTypes.sh, packages/safe-service-client/tests/e2e/addSafeDelegate.test.ts, packages/safe-service-client/tests/e2e/getBalances.test.ts, packages/safe-service-client/tests/e2e/getCollectibles.test.ts, packages/safe-service-client/tests/e2e/getIncomingTransactions.test.ts, packages/safe-service-client/tests/e2e/getMultisigTransactions.test.ts, packages/safe-service-client/tests/e2e/getNextNonce.test.ts, packages/safe-service-client/tests/e2e/getPendingTransactions.test.ts, packages/safe-service-client/tests/e2e/getSafeDelegates.test.ts, packages/safe-service-client/tests/e2e/getSafeInfo.test.ts, packages/safe-service-client/tests/e2e/getSafesByModule.test.ts, packages/safe-service-client/tests/e2e/getToken.test.ts, packages/safe-service-client/tests/e2e/getTransaction.test.ts, packages/safe-service-client/tests/e2e/getTransactionConfirmations.test.ts, packages/safe-service-client/tests/e2e/getUsdBalances.test.ts, packages/safe-service-client/tests/e2e/removeAllSafeDelegates.test.ts, packages/safe-service-client/tests/e2e/removeSafeDelegate.test.ts, packages/safe-service-client/tests/endpoint/index.test.ts, packages/safe-service-client/tests/utils/config.ts
=> Migrate Rinkeby tests to Goerli

packages/safe-core-sdk-types/src/ethereumLibs/EthAdapter.ts, packages/safe-core-sdk-types/src/types.ts, packages/safe-core-sdk/README.md, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/tests/execution.test.ts, packages/safe-ethers-lib/src/types.ts, packages/safe-web3-lib/src/types.ts
=> Support EIP-1559

.github/workflows/cla.yml
- Updates the allowlist in the CLA 🥲
=> Update CLA allowlist

.gitignore, packages/safe-core-sdk/src/utils/signatures/index.ts, packages/safe-ethers-adapters/.env.sample, packages/safe-service-client/scripts/generateTxServiceTypes.sh, packages/safe-service-client/tests/e2e/getMultisigTransactions.test.ts, packages/safe-service-client/tests/e2e/getNextNonce.test.ts, packages/safe-service-client/tests/e2e/getPendingTransactions.test.ts, packages/safe-service-client/tests/endpoint/index.test.ts, packages/safe-service-client/tests/utils/config.ts
This came out from an attempt to resolve #214, I couldn't reproduce the error from the issue, but thought we could use some better comments and name variables for the V adjustment code
=> Refactor signature's V value adjustment code, better naming and comments

guides/integrating-the-safe-core-sdk.md, packages/safe-core-sdk-types/src/contracts/GnosisSafeContract.ts, packages/safe-core-sdk/README.md, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/tests/execution.test.ts, packages/safe-ethers-lib/src/contracts/GnosisSafe/GnosisSafeContractEthers.ts, packages/safe-web3-lib/src/contracts/GnosisSafe/GnosisSafeContractWeb3.ts
This PR adds the method `isValidTransaction` that returns a boolean value and allows to check if a transaction will be executed with or without errors.
=> Check if a transaction is valid

packages/safe-core-sdk/README.md
Resolves https://github.com/safe-global/safe-core-sdk/issues/280
=> Fix guide URL in README file

packages/safe-core-sdk/src/Safe.ts
This PR removes the warning displayed when signing a transaction
=> Remove warning when signing a transaction

packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-utils/package.json, packages/safe-core-sdk/package.json, packages/safe-ethers-adapters/package.json, packages/safe-ethers-lib/package.json, packages/safe-service-client/package.json, packages/safe-web3-lib/package.json
- #312 
It basically updates the `safe-core-sdk-types` version number (and all the packages that use it)
=> Fix SafeMultisigTransactionResponse missing type

.github/workflows/cla.yml, README.md, packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-utils/package.json, packages/safe-core-sdk/README.md, packages/safe-core-sdk/package.json, packages/safe-ethers-adapters/package.json, packages/safe-ethers-lib/package.json, packages/safe-service-client/package.json, packages/safe-web3-lib/package.json
Update CLA action to unified CLA version and updates link to safe.global CLA
Updates the action to align the other repos and links to the safe.global CLA
=> chore: update CLA action and remove Gnosis references

packages/safe-ethers-adapters/package.json, packages/safe-service-client/README.md, packages/safe-service-client/package.json, packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/src/SafeTransactionService.ts, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts, packages/safe-service-client/src/utils/index.ts, packages/safe-service-client/tests/e2e/getCollectibles.test.ts, packages/safe-service-client/tests/endpoint/index.test.ts, packages/safe-web3-lib/package.json, packages/safe-web3-lib/src/Web3Adapter.ts, yarn.lock
- Safe Service Client v2
- [Update collectibles endpoint to v2](https://github.com/safe-global/safe-core-sdk/commit/0bed028eaca1aca3aa234ab59b21597b1c9566fe)
=> Merge Development into Main

packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json
Updates the packages versions:
=> Version update

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json
Updates the version number of the `safe-core-sdk-types` package
=> chore(safe-core-sdk-types): update version number to v1.10.0

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json
Merges `developement` branch into `main`
=> Merge developement branch into main branch

package.json, packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json, yarn.lock
Fix aliases not being resolved after build in the dist directories
=> fix: Alias in dist

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json
Prepare release version on packages
=> chore: prepare release

packages/api-kit/src/utils/httpRequests.ts, packages/safe-ethers-adapters/src/signer.ts, packages/safe-ethers-adapters/src/utils.ts, packages/safe-ethers-adapters/tests/signer.test.ts
Fixes ESLint errors to pass the ESLint check in PRs
=> chore: fix eslint errors

packages/protocol-kit/README.md
```js
const safeAccountConfig: SafeAccountConfig = {
owners,
threshold,
to, // Optional
data, // Optional
fallbackHandler, // Optional
paymentToken, // Optional
payment, // Optional
paymentReceiver // Optional
}
const saltNonce = '<YOUR_CUSTOM_VALUE>'
const safeSdk = await safeFactory.deploySafe({ safeAccountConfig, saltNonce })
```
=> docs: update salt nonce param reference in the deploy method

packages/protocol-kit/README.md
Adds some documentation about Safe creation and connection using the new `predictedSafe` property.
=> chore(protocol-kit): update predicted Safe documentation

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/README.md, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json
Merge `main` into `development`
=> chore: merge `main` into `development`

packages/account-abstraction-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json
=> chore: set versions

README.md, playground/config/run.ts
This PR updates the playground section in the main README file.
=> chore: update playground docs

packages/auth-kit/README.md, packages/onramp-kit/README.md
Update READMEs for `auth-kit` and `onramp-kit` with links to the specific "Guides" and "Reference" sections
=> doc: Update READMEs

README.md
Use the proper logo for this repo
=> chore: update Safe{Core} SDK logo

packages/auth-kit/README.md, packages/onramp-kit/README.md, packages/onramp-kit/example/client/.env.sample, packages/onramp-kit/src/packs/monerium/signatures.ts, packages/protocol-kit/README.md, packages/protocol-kit/src/utils/signatures/utils.ts, packages/relay-kit/README.md, playground/api-kit/confirm-transaction.ts, playground/api-kit/execute-transaction.ts, playground/api-kit/propose-transaction.ts
Merge docs links to `development`
=> chre: update links pointing to the Safe docs (#489)

packages/onramp-kit/example/client/package.json, packages/onramp-kit/example/client/src/AuthContext.tsx, packages/onramp-kit/example/client/src/components/monerium/Monerium.tsx, packages/onramp-kit/example/client/yarn.lock
Upgrade onramp-kit example app to use new auth-kit classes
=> chore: Update onramp example

packages/onramp-kit/src/packs/monerium/MoneriumPack.ts
Having `SafeMoneriumClient` public allow users to check in advance if the initial transaction to link the account was already placed or is in the pending list for giving feedback to the user
Currently you need to do that after the `open()` method so after the user is logged in
=> feature(onramp-kit): Make `SafeMoneriumClient` public

packages/account-abstraction-kit/src/AccountAbstraction.ts, packages/account-abstraction-kit/src/types/index.ts
Simplifies account abstraction kit now that the relay-kit contains logic to deploy the Safe if necessary and encode the execute transaction
=> Account abstraction kit code cleanup

.github/workflows/cla.yml
Fix CLA link to point to the correct document
=> chore: fix CLA link not working

packages/protocol-kit/package.json, packages/protocol-kit/tests/unit/eip-712.test.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/462
We have a missing test script in the `protocol-kit` for the unit tests
=> fix: Add script to execute the tests

packages/onramp-kit/package.json, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.test.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts, packages/onramp-kit/src/packs/monerium/signatures.ts, yarn.lock
This PR improves the `onramp-kit` bundle size
We are removing the ethers complete lib package and using the smaller ones
- #516
=> feat(onramp-kit): Reduce bundle size removing ethers complete package

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, playground/relay-kit/paid-transaction.ts, playground/relay-kit/sponsored-transaction.ts
Set packages versions to deploy
=> Set packages versions

packages/protocol-kit/src/utils/transactions/gas.ts
Update `parseSafeTxGasErrorResponse` for Improved safeTxGas Parsing Across Providers
=> fix: `parseSafeTxGasErrorResponse` to improve error handling across providers

packages/protocol-kit/src/utils/transactions/gas.ts
=> Update parseSafeTxGasErrorResponse for Enhanced Provider Error Handling

packages/protocol-kit/src/utils/transactions/gas.ts
=> fix decodeSafeTxGas

packages/api-kit/tests/e2e/getServiceMastercopiesInfo.test.ts, packages/protocol-kit/src/utils/transactions/gas.ts
=> fix encodedSafeTxGas

packages/onramp-kit/example/client/src/components/monerium/Monerium.tsx, packages/onramp-kit/example/client/yarn.lock, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts, yarn.lock
We are adjusting some things in the [Monerium external PR](https://github.com/safe-global/safe-core-sdk/pull/591) to update the SDK
=> fix(onramp-kit): Some improvement to Monerium PR

packages/api-kit/hardhat.config.ts
Removes a pending INFURA_KEY prop from #641
=> fix(api-kit): pending INFURA_KEY

.github/workflows/test.yml, packages/api-kit/package.json, packages/protocol-kit/package.json, yarn.lock
Coverage report was having issues when being pushed in different action steps and slow network. Not we will use an unique push step sending all the coverage reports at once.
=> fix: use one push for all coverage reports

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/example/client/package.json, packages/onramp-kit/example/client/yarn.lock, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json
Merge versioning to development
=> Merge release to development

packages/api-kit/src/utils/config.ts
Add Base Sepolia transaction service url to api-kit
=> chore(api-kit): Add Base Sepolia support

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json
Merge back release versioning to development
=> chore: mergeback release to development

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/SafeOperation.ts, packages/relay-kit/src/packs/safe-4337/types.ts, playground/relay-kit/usdc-transfer-4337-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20.ts, playground/relay-kit/usdc-transfer-4337-sponsored-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-sponsored.ts, playground/relay-kit/usdc-transfer-4337.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/734
Adding support for the `validUntil` and `validAfter` dates
https://eips.ethereum.org/EIPS/eip-4337
=> feat(relay-kit): Add support for time-range dates in the Safe4337Pack

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json
=> chore: mergeback to development

packages/protocol-kit/src/contracts/BaseContract.ts
=> fix BaseContract provider

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json
Mergeback safe-deployments release back to `development`
=> Mergeback release to `development`

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/api-kit/tests/e2e/getSafeDelegates.test.ts, packages/api-kit/tests/e2e/getSafeOperationsByAddress.test.ts
Fixes some failing e2e tests for the api-kit.
=> fix(api-kit): Fix failing e2e tests

packages/api-kit/tests/e2e/getSafeDelegates.test.ts
Some follow-up fixes to #897 due to tests still being flaky.
=> fix(api-kit): Fix flaky e2e tests

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/tests/endpoint/index.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/estimators/PimlicoFeeEstimator.ts, packages/safe-kit/src/extensions/safe-operations/SafeOperationClient.ts, playground/relay-kit/api-kit-interoperability.ts, playground/relay-kit/usdc-transfer-4337-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20.ts, playground/relay-kit/usdc-transfer-4337-sponsored-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-sponsored.ts, playground/relay-kit/usdc-transfer-4337.ts, playground/safe-kit/send-safe-operation.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/903
- Convert dates (validAfter and validUntil) for transaction service
- Concat paymaster and paymasterData fields from transaction service
- Adjust pimlico estimator
- use addSafeOperation() with the API response instead calculating values
- Update bundler to v2
- Fix issue in send-safe-operations playground
- Use preparedSignature from transaction service
=> fix: 4337 issues

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/types.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/900 and #896 
- Added new types for paymaster options making it clear what properties to use
=> feat(relay-kit): Improve `Safe4337Pack` paymaster types

packages/api-kit/package.json, packages/api-kit/tests/e2e/getSafeOperationsByAddress.test.ts, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/protocol-kit/tests/e2e/eip1271.test.ts, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-kit/package.json
Mergeback version changes to development
=> Mergeback release to dev

packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-kit/package.json
Merge back release versioning back to development
=> Mergeback release to development

packages/protocol-kit/src/Safe.ts, packages/sdk-starter-kit/src/BaseClient.ts
Uses the methods under Safe instead the OwnerManager
=> feat(sdk-starter-kit): Improve owner management

.github/workflows/protocol-kit-e2e-test.yml, packages/api-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/relay-kit/src/packs/safe-4337/estimators/PimlicoFeeEstimator.test.ts, packages/sdk-starter-kit/package.json, packages/sdk-starter-kit/src/extensions/safe-operations/safeOperations.ts, packages/sdk-starter-kit/src/extensions/safe-operations/types.ts, packages/testing-kit/package.json, packages/testing-kit/tsconfig.build.json, packages/testing-kit/tsconfig.json
Fix some leftovers in the release and push the final versions
=> chore: fix release comments

packages/sdk-starter-kit/src/BaseClient.ts
=> fix(sdk-starter-kit): Rename method

packages/protocol-kit/package.json, packages/relay-kit/package.json, yarn.lock
Bumps safe-modules-deployments to latest version to add missing addresses.
https://github.com/safe-global/safe-modules-deployments/compare/v2.2.1...v2.2.4
=> chore: bump safe-modules-deployments

packages/protocol-kit/src/Safe.ts
=> fix(protocol-kit): fixed missing `deploymentType` param in the`encodeSetupCallData` in the `createSafeDeploymentTransaction` method

packages/api-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/sdk-starter-kit/package.json, packages/testing-kit/package.json
Mergeback release versions to `development`
=> chore: mergeback release to `development`

LICENSE.md
This PR:
- Updates the license year to 2025
=> chore: Update license year

packages/api-kit/package.json, packages/relay-kit/package.json, packages/relay-kit/src/packs/safe-4337/utils.ts, packages/relay-kit/src/packs/safe-4337/utils/getRelayKitVersion.ts, packages/sdk-starter-kit/package.json, yarn.lock
```
@safe-global/relay-kit: 3.4.2
@safe-global/sdk-starter-kit: 1.1.4
```
- #1118  
- #1115
=> Prepare release

packages/relay-kit/package.json
=> fix(relay-kit): Add `semver` dep in the relay-kit

.github/workflows/api-kit-e2e-test.yml, .github/workflows/protocol-kit-e2e-test.yml, guides/integrating-the-safe-core-sdk.md, packages/api-kit/package.json, packages/api-kit/tests/utils/setupKits.ts, packages/protocol-kit/package.json, packages/protocol-kit/tests/e2e/utils/setupProvider.ts, yarn.lock
=> chore: remove web3 from tests and dependencies

packages/api-kit/package.json, packages/protocol-kit/package.json, packages/protocol-kit/src/utils/getProtocolKitVersion.ts, packages/relay-kit/package.json, packages/relay-kit/src/packs/safe-4337/utils/getRelayKitVersion.ts, packages/sdk-starter-kit/package.json
=> chore: mergeback release

packages/protocol-kit/src/utils/eip-3770/config.ts
change shortname for fxcore to pundiai
https://chainlist.org/chain/530
shortname for dhobyghaut: no changes
https://chainlist.org/chain/90001
pundiai 1.4.1 safe deployment: no changes
https://github.com/safe-global/safe-deployments/pull/663
dhobyghaut 1.4.1 safe deployment: no changes
https://github.com/safe-global/safe-deployments/pull/652
=> change shortname for fxcore to pundiai

README.md, packages/sdk-starter-kit/src/SafeClient.ts, playground/README.md, playground/api-kit/confirm-transaction.ts, playground/api-kit/execute-transaction.ts, playground/api-kit/propose-transaction.ts, playground/protocol-kit/create-execute-transaction.ts, playground/protocol-kit/deploy-safe.ts, playground/protocol-kit/estimate-gas.ts, playground/protocol-kit/generate-safe-address.ts, playground/protocol-kit/replicate-address.ts, playground/protocol-kit/validate-signatures.ts, playground/relay-kit/.env-sample, playground/relay-kit/userop-counterfactual.ts, playground/relay-kit/userop-erc20-paymaster-counterfactual.ts, playground/relay-kit/userop-erc20-paymaster.ts, playground/relay-kit/userop-parallel-execution.ts, playground/relay-kit/userop-verifying-paymaster-counterfactual.ts, playground/relay-kit/userop-verifying-paymaster.ts, playground/relay-kit/userop.ts, playground/sdk-starter-kit/owner-management.ts, playground/sdk-starter-kit/send-off-chain-message.ts, playground/sdk-starter-kit/send-on-chain-message.ts, playground/sdk-starter-kit/send-safe-operation.ts, playground/sdk-starter-kit/send-transactions.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/1174
=> feat: Improve playgrounds information
