safe-global/safe-core-sdk

.github/workflows/test.yml, README.md, src/EthersSafe.ts, src/Safe.ts, src/abis/SafeAbiV1-2-0.json, src/index.ts, src/utils/signatures.ts, src/utils/transactions.ts, tests/core.test.ts, tests/signatures.test.ts
Add read methods to access the data from the Safe contract
=> Add read methods

packages/safe-core-sdk/README.md, packages/safe-core-sdk/src/EthersSafe.ts, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/index.ts, packages/safe-core-sdk/tests/execution.test.ts
Adds an `options` parameter to `executeTransaction()` in order to override the `gasLimit` or set a `gasPrice`.
See https://github.com/gnosis/safe-core-sdk/issues/43
=> Allow to override transaction options

packages/safe-core-sdk/README.md
=> fix small typo in safe-core-sdk readme

packages/safe-core-sdk/README.md
=> Fix safe-core-sdk README

packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/tests/index.test.ts
https://safe-transaction.rinkeby.gnosis.io/api/v1/owners/0xA66A5686D5c3A42C0b6c76FEd05e58C6bc851E9f -> 404
https://safe-transaction.rinkeby.gnosis.io/api/v1/owners/0xA66A5686D5c3A42C0b6c76FEd05e58C6bc851E9f/safes/ -> 200
https://safe-transaction.gnosis.io/api/v1/owners/0xA66A5686D5c3A42C0b6c76FEd05e58C6bc851E9f -> 404
https://safe-transaction.gnosis.io/api/v1/owners/0xA66A5686D5c3A42C0b6c76FEd05e58C6bc851E9f/safes/ -> 200
=> Use correct endpoint for getSafesByOwner

packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/tests/execution.test.ts
Throws the exception `Not enough Ether funds` when the Safe Ether balance is lower than the value of a tx that will be executed
=> Throw exception if there are not enough funds

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/cla.yml, .github/workflows/typedoc.yml
This PR adds a PR template to make linking PRs to issues easier.
It also introduces a github action that generates HTML docs based on types and deploys them to GitHub Pages.
Once this is merged, GitHub Pages need to be enabled.
=> Add a PR template and typedoc site generation

.gitignore, packages/safe-service-client/scripts/generateTxServiceTypes.sh, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts
Makes the property `signatures` nullable in the type `SafeMultisigTransactionResponse` returned by the Safe Transaction Service.
=> Make signatures nullable in SafeMultisigTransactionResponse

packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/utils/index.ts, packages/safe-core-sdk/tests/createTransaction.test.ts
Resolves #101 
- Considers that transaction arrays with length = 1 are single transactions, not Multisend.
- Does not accept transaction arrays with length = 0
- Tests are updated to consider these use cases
=> Multisend fix

packages/safe-core-sdk/package.json, packages/safe-core-sdk/src/managers/contractManager.ts
The Master Copy address is obtained from `safe-deployments` based on the network and contract version.
When the SDK is initialized, to obtain the contract version we need to instantiate the contract and call the `VERSION()` method. This instance is called `temporarySafeContract` and uses the `SAFE_BASE_VERSION` (v1.1.1) just to obtain the contract version and instantiate the contract again with the real one.
When working with L2 contracts (GnosisSafeL2.sol) and Web3 provider (not Ethers), it fails because it tries to get the ABI from `safe-deployments` for the version v1.1.1, but that version does not have a GnosisSafeL2.sol contract. (It works using the flag `isL1SafeContract=true` but that forces to use a different Master Copy).
Uses v1.3.0 as the temporary Safe contract to prevent …
=> Fix L2 initialization

packages/safe-core-sdk/package.json, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/index.ts, packages/safe-core-sdk/src/utils/safeVersions.ts, packages/safe-core-sdk/src/utils/transactions/utils.ts, packages/safe-core-sdk/tests/createTransaction.test.ts, packages/safe-core-sdk/tests/moduleManager.test.ts, packages/safe-core-sdk/tests/ownerManager.test.ts, packages/safe-core-sdk/tests/threshold.test.ts, packages/safe-service-client/tests/endpoint.test.ts, yarn.lock
=> Set safeTxGas=0 when safeVersion>=1.3.0

packages/safe-core-sdk/src/contracts/GnosisSafe/v1.1.1/GnosisSafeContract_V1_1_1_Ethers.ts, packages/safe-core-sdk/src/contracts/GnosisSafe/v1.1.1/GnosisSafeContract_V1_1_1_Web3.ts
`super.contract` is undefined in classes `GnosisSafeContract_V1_1_1_Ethers` and `GnosisSafeContract_V1_1_1_Web3`
Call `this.contract`
=> Fix contract calls in class GnosisSafeContract_V1_1_1

packages/safe-core-sdk/package.json, yarn.lock
Update safe-deployments dependency to v1.7.0 in Safe Core SDK
=> Update safe-deployments dependency to v1.7.0

.github/workflows/test_ethers_V1_2_0.yml, .github/workflows/test_ethers_V1_3_0.yml, .github/workflows/test_web3_V1_2_0.yml, .github/workflows/test_web3_V1_3_0.yml, packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryEthersContract.ts, packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts, packages/safe-core-sdk/src/ethereumLibs/EthAdapter.ts, packages/safe-core-sdk/src/ethereumLibs/EthersAdapter.ts, packages/safe-core-sdk/src/ethereumLibs/Web3Adapter.ts, packages/safe-core-sdk/src/managers/contractManager.ts, packages/safe-core-sdk/src/safeFactory/index.ts, packages/safe-core-sdk/src/types/index.ts, packages/safe-core-sdk/tests/contractManager.test.ts, packages/safe-core-sdk/tests/core.test.ts, packages/safe-core-sdk/tests/createTransaction.test.ts, packages/safe-core-sdk/tests/ethAdapters.test.ts, packages/safe-core-sdk/tests/execution.test.ts, packages/safe-core-sdk/tests/moduleManager.test.ts, packages/safe-core-sdk/tests/offChainSignatures.test.ts, packages/safe-core-sdk/tests/onChainSignatures.test.ts, packages/safe-core-sdk/tests/ownerManager.test.ts, packages/safe-core-sdk/tests/safeFactory.test.ts, packages/safe-core-sdk/tests/threshold.test.ts, packages/safe-core-sdk/tests/utils/setupContractNetworks.ts, packages/safe-core-sdk/tests/utils/setupContracts.ts
=> Fix Web3 tests

packages/safe-core-sdk/package.json
Adding version 1.8.0 of safe-deployment with Moonbeam configuration
Resolves # Unable to access features of SDK on moonbeam network
https://github.com/gnosis/safe-deployments/pull/58
CC: @germartinez
=> Update safe-deployments to v1.8.0

.github/workflows/test.yml, package.json
I've copied the same `yarn install` job as in safe-react.
It correctly uses a frozen lock file which ensures idempotent builds.
=> Chore: use yarn cache in the CI script

packages/safe-core-sdk/README.md
Fixed README of `safe-core-sdk`-package regarding the import of `Safe` 
Wrong:
`import { Safe, SafeFactory, SafeAccountConfig } from '@gnosis.pm/safe-core-sdk'`
Correct:
`import Safe, { SafeFactory, SafeAccountConfig } from '@gnosis.pm/safe-core-sdk'` 
because Safe is `export default`: https://github.com/gnosis/safe-core-sdk/blob/main/packages/safe-core-sdk/src/Safe.ts#L602
This PR fixes the corresponding example in the README.
=> Fixed import-statement of 'Safe' that is 'export default' now

packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts, packages/safe-core-sdk/src/managers/contractManager.ts, packages/safe-core-sdk/src/safeFactory/index.ts, packages/safe-core-sdk/tests/contractManager.test.ts, packages/safe-core-sdk/tests/safeFactory.test.ts
Resolves #165 
- In the `SafeFactory` class, inside the method `getContract` was a call to the method `getSafeContractDeployment` where the safeVersion was set to the last current version. This was wrong.
- Refactor the methods that return the instances of the Safe contracts:
- The methods `getProxyFactoryContract`, `getMultiSendContract` and `getSafeContract` were extracted to a different file.
- There were two different implementations of `getSafeContract` before (one with `customSafeAddress` as a prop and other without it). These two were also merged in one.
=> Fix safe version and refactor safe deployments functions

packages/safe-core-sdk-types/package.json, packages/safe-core-sdk/package.json, packages/safe-ethers-adapters/package.json, yarn.lock
Update `safe-deployments` to v1.9.0
=> Update safe-deployments v1.9.0

.github/workflows/e2e-test.yml, .github/workflows/test.yml, .github/workflows/test_ethers_V1_2_0.yml, .github/workflows/test_ethers_V1_3_0.yml, .github/workflows/test_web3_V1_2_0.yml, .github/workflows/test_web3_V1_3_0.yml
Updates the event triggers in the Github actions to reduce the number of builds and duplicate tests
=> Update github actions event triggers

packages/safe-core-sdk-types/src/contracts/GnosisSafeProxyFactoryContract.ts, packages/safe-core-sdk/src/safeFactory/index.ts, packages/safe-core-sdk/tests/safeFactory.test.ts, packages/safe-ethers-lib/src/contracts/GnosisSafe/GnosisSafeContractEthers.ts, packages/safe-ethers-lib/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryEthersContract.ts, packages/safe-ethers-lib/src/index.ts, packages/safe-ethers-lib/src/types.ts, packages/safe-ethers-lib/src/utils/index.ts, packages/safe-web3-lib/src/contracts/GnosisSafe/GnosisSafeContractWeb3.ts, packages/safe-web3-lib/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts, packages/safe-web3-lib/src/index.ts, packages/safe-web3-lib/src/types.ts, packages/safe-web3-lib/src/utils/index.ts
Adds a callback to the `deploySafe` method in the `SafeFactory` class.
This callback receives as a parameter the `tcxHash` of the deployment transaction, allowing to track the transaction outside of the SDK, in parallel, meanwhile the deployment is being executed.
```js
const callback = (txHash: string): void => {
console.log({ txHash })
}
const safeFactory = await SafeFactory.create({ ethAdapter })
const deploySafeProps: DeploySafeProps = { safeAccountConfig, callback }
const safe = await safeFactory.deploySafe(deploySafeProps)
```
=> Add a callback to Safe deployment

packages/safe-core-sdk-types/package.json, packages/safe-core-sdk-types/src/types.ts, packages/safe-core-sdk-utils/package.json, packages/safe-core-sdk-utils/src/eip-712/index.ts, packages/safe-core-sdk-utils/tests/eip-712.test.ts, packages/safe-core-sdk/package.json, packages/safe-core-sdk/src/utils/signatures/index.ts, packages/safe-ethers-lib/package.json, packages/safe-ethers-lib/src/EthersAdapter.ts, packages/safe-service-client/package.json, packages/safe-web3-lib/package.json
Fixes the error `[Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)](https://ethereum.stackexchange.com/questions/130776/error-invalid-bignumber-value-argument-value-value-undefined-code-invalid)` for Safes with version `<v1.3.0`.
This issue was caused because `chainId` had a wrong type making `signer._signTypedData()` complain about it.
=> Fix signTypedData

packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/tests/execution.test.ts
Avoids modifying the transaction object that is passed to the `executeTransaction` method in the SDK.
=> Make executeTransaction immutable

packages/safe-core-sdk/src/Safe.ts
This PR makes immutable the `signTransaction` method from the Core SDK by not adding the signature to the passed `safeTransaction` argument.
=> Make signTransaction method immutable

packages/safe-core-sdk-types/src/ethereumLibs/EthAdapter.ts, packages/safe-core-sdk-types/src/types.ts, packages/safe-core-sdk/README.md, packages/safe-core-sdk/tests/execution.test.ts, packages/safe-ethers-lib/src/EthersAdapter.ts, packages/safe-ethers-lib/src/types.ts, packages/safe-web3-lib/src/Web3Adapter.ts, packages/safe-web3-lib/src/types.ts
Allows to specify the nonce from the sender wallet when executing a Safe transaction via the Core SDK.
=> Add user nonce to TransactionOptions type

packages/safe-core-sdk/README.md, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts, packages/safe-core-sdk/src/safeFactory/index.ts, packages/safe-core-sdk/src/types/index.ts, packages/safe-core-sdk/tests/contractManager.test.ts, packages/safe-core-sdk/tests/ethAdapters.test.ts, packages/safe-core-sdk/tests/moduleManager.test.ts, packages/safe-core-sdk/tests/ownerManager.test.ts, packages/safe-core-sdk/tests/safeFactory.test.ts, packages/safe-core-sdk/tests/threshold.test.ts, packages/safe-ethers-lib/src/EthersAdapter.ts, packages/safe-ethers-lib/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryEthersContract.ts, packages/safe-web3-lib/src/Web3Adapter.ts, packages/safe-web3-lib/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts
Taking advantage of the next mayor release, this PR:
- Renames methods that return a Safe transaction that modifies the Safe settings.
Example: `const safeTx = getAddOwnerTx(...)` -> `const safeTx = createAddOwnerTx(...)`
- Renames contract names in error messages
Example: `Error: [...] Multi Send contract [...]` -> `Error: [...] MultiSend contract [...]`
- Updates tests and documentation accordingly
=> Rename methods and error messages

packages/safe-core-sdk-types/src/types.ts
Updates the type of the `nonce` property inside `TransactionOptions` from `number` to `number | string` to increase the flexibility.
=> Update nonce type in `TransactionOptions`

guides/integrating-the-safe-core-sdk.md, packages/safe-core-sdk-types/src/contracts/CreateCallContract.ts, packages/safe-core-sdk-types/src/ethereumLibs/EthAdapter.ts, packages/safe-core-sdk-types/src/index.ts, packages/safe-core-sdk/README.md, packages/safe-core-sdk/contracts/Deps_V1_3_0.sol, packages/safe-core-sdk/hardhat/deploy/deploy-contracts.ts, packages/safe-core-sdk/src/contracts/config.ts, packages/safe-core-sdk/src/contracts/safeDeploymentContracts.ts, packages/safe-core-sdk/src/types/index.ts, packages/safe-core-sdk/tests/contractManager.test.ts, packages/safe-core-sdk/tests/ethAdapters.test.ts, packages/safe-core-sdk/tests/safeFactory.test.ts, packages/safe-core-sdk/tests/utils/setupContractNetworks.ts, packages/safe-core-sdk/tests/utils/setupContracts.ts, packages/safe-ethers-lib/contracts/Deps_V1_3_0.sol, packages/safe-ethers-lib/scripts/generateTypechainFiles.ts, packages/safe-ethers-lib/src/EthersAdapter.ts, packages/safe-ethers-lib/src/contracts/CreateCall/CreateCallEthersContract.ts, packages/safe-ethers-lib/src/contracts/CreateCall/v1.3.0/CreateCallEthersContract_V1_3_0_Ethers.ts, packages/safe-ethers-lib/src/contracts/contractInstancesEthers.ts, packages/safe-web3-lib/contracts/Deps_V1_3_0.sol, packages/safe-web3-lib/scripts/generateTypechainFiles.ts, packages/safe-web3-lib/src/Web3Adapter.ts, packages/safe-web3-lib/src/contracts/CreateCall/CreateCallWeb3Contract.ts, packages/safe-web3-lib/src/contracts/CreateCall/v1.3.0/CreateCallEthersContract_V1_3_0_Web3.ts, packages/safe-web3-lib/src/contracts/contractInstancesWeb3.ts
- This PR implements: https://github.com/safe-global/safe-core-sdk/issues/276
- Completes the similar addition of SignMessageLib library
- Adds tests
=> Support CreateCall contract library

guides/integrating-the-safe-core-sdk.md, packages/safe-ethers-adapters/README.md, packages/safe-service-client/README.md
Safe Transaction Service URL's are being migrated during the month of October.
Specifically for Mainnet:
```
safe-transaction.mainnet.gnosis.io   -> safe-transaction-mainnet.safe.global  (DATE: 22-10-24 - 9am CEST)
safe-transaction.gnosis.io           -> safe-transaction-mainnet.safe.global  (DATE: 22-10-24 - 9am CEST)
```
This PR updates the old URLs with the new ones.
Do not merge before the 24th of October!
=> Update Mainnet Transaction Service URL (do not merge yet!)

packages/safe-ethers-adapters/README.md
- Updates the instructions for the safe-ethers-adapters package, using the correct types/values.
- Fixes the examples link. Currently, in NPM, it redirects to the `/examples` root directory of the repo rather than the package's /examples.
=> Update README.md for safe-ethers-adapters

.eslintrc.js, packages/safe-core-sdk/src/utils/transactions/utils.ts, packages/safe-core-sdk/tests/createTransaction.test.ts
- Resolves #292 
- Updates eslint configuration after prettier plugin 8.0.0 update - more info [here](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21) (it's from early 2021 lol)
Currently, the SDK doesn't take into account the `safeTxGas` unless you pass the full suite of relay-related params with the most important being `gasPrice`
In my opinion, it's not 100% justified because `safeTxGas` still has some use cases, like ensuring that enough gas is supplied for the transaction. I'm sure there's more that advanced EVM ninjas can share.
=> respect passed safeTxGas if the safe is 1.3.0

guides/integrating-the-safe-core-sdk.md, packages/safe-core-sdk-types/src/types.ts, packages/safe-core-sdk/src/Safe.ts, packages/safe-core-sdk/src/index.ts, packages/safe-core-sdk/src/utils/index.ts, packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/src/SafeTransactionService.ts, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts, playground/deploy-safe.ts, playground/execute-transaction.ts, yarn.lock
This pull requests facilitates executing or signing of a transaction right after it is retrieved from the Transaction Service by allowing the methods `signTransaction()` and `executeTransaction()` to receive the transaction type returned by the service and handled that internally.
It also exposes the new method `toSafeTransactionType()` that is in charge of doing the type conversion mentioned before. 
Check https://github.com/safe-global/safe-core-sdk/issues/125
=> Operate with the transaction type returned by the Transaction Service

packages/safe-core-sdk/src/utils/transactions/utils.ts, packages/safe-core-sdk/tests/createTransaction.test.ts
Resolves [#1343](https://github.com/safe-global/web-core/issues/1343)
If a transaction is created with 0 safeTxGas in the web-core UI and another owner tries to sign it, the `createTransaction` call from the SDK will return a non 0 safeTxGas which causes issues with the existing txData (such as gasLimit estimation failing).
Narrow the condition to check for `undefined` so that a `safeTxGas` of 0 is caught by it.
=> fix: Handle 0 safeTxGas when passed to createTransaction call

packages/safe-ethers-adapters/package.json, packages/safe-service-client/README.md, packages/safe-service-client/package.json, packages/safe-service-client/src/SafeServiceClient.ts, packages/safe-service-client/src/SafeTransactionService.ts, packages/safe-service-client/src/types/safeTransactionServiceTypes.ts, packages/safe-service-client/src/utils/index.ts, packages/safe-service-client/tests/e2e/getCollectibles.test.ts, packages/safe-service-client/tests/endpoint/index.test.ts, packages/safe-web3-lib/package.json, packages/safe-web3-lib/src/Web3Adapter.ts, yarn.lock
- [BREAKING CHANGE] Upgrade the `collectibles` endpoint to v2 with pagination support.
- Fix a web3 types issue now that @types/web3 was deprecated with web3@v4 launch.
- Updated all endpoints to have versioning.
- [BREAKING CHANGE] Use collectibles v2 and add new properties to the endpoint
- Use fixed version of `@types/web3` until web3@v4 migration or can be changed by web3@v1 native types.
=> Update collectibles endpoint to v2

packages/account-abstraction-kit/README.md, packages/account-abstraction-kit/package.json, packages/account-abstraction-kit/scripts/typechain.ts, packages/account-abstraction-kit/src/AccountAbstraction.ts, packages/account-abstraction-kit/src/constants/index.ts, packages/account-abstraction-kit/src/index.ts, packages/account-abstraction-kit/src/types/index.ts, packages/account-abstraction-kit/src/utils/contracts.ts, packages/account-abstraction-kit/src/utils/deployments.ts, packages/account-abstraction-kit/src/utils/index.ts, packages/account-abstraction-kit/tsconfig.json
Adds the package `account-abstraction-sdk` to this monorepo.
The package is refactored in the [next PR](https://github.com/safe-global/safe-core-sdk/pull/364) so it is easier to track the changes
=> Add account-abstraction-sdk

packages/account-abstraction-kit/src/AccountAbstraction.ts, packages/account-abstraction-kit/src/utils/contracts.ts, packages/protocol-kit/src/adapters/ethers/EthersAdapter.ts, packages/protocol-kit/src/adapters/web3/Web3Adapter.ts, packages/protocol-kit/src/contracts/safeDeploymentContracts.ts, packages/protocol-kit/src/managers/contractManager.ts, packages/protocol-kit/src/safeFactory/index.ts, packages/protocol-kit/tests/e2e/ethAdapters.test.ts, packages/protocol-kit/tests/e2e/utils/setupEthAdapter.ts, packages/protocol-kit/tests/e2e/utils/setupTestNetwork.ts, packages/safe-core-sdk-types/src/ethereumLibs/EthAdapter.ts
- Removes unnecessary `chainId` param from the methods that get the contract instances
- Updates the tests
=> chore: remove chainId from contracts getters

packages/api-kit/src/types/safeTransactionServiceTypes.ts
TokenInfoListResponse results is a circular reference. As per the API docs, it should be TokenInfoResponse.
Resolves an incorrect type in `api-kit`
Properly define TokenInfoListResponse type
=> fix: TokenInfoListResponse results type

packages/auth-kit/src/packs/web3auth/Web3AuthAdapter.ts
Metamask does not allow to get the private key so if user try to connect using a regular Wallet an exception is thrown
=> fix(auth-kit): Remove log causing wallet connection error

packages/auth-kit/example/src/App.tsx, packages/auth-kit/example/src/AppBar.tsx, packages/auth-kit/src/SafeAuthKit.ts, packages/auth-kit/src/packs/web3auth/Web3AuthAdapter.ts, packages/auth-kit/src/types.ts
It allow users to use the [`getUserInfo()`](https://web3auth.io/docs/pnp/features/server-side-verification/social-login-users#getuserinfo) method from web3 auth
It expose it through the common interface as new providers can expose this information as well with their own methods
NOTE: It fix a bug where the provider was not initialised if i try to make a page refresh
=> feat(auth-kit): Expose the getUserInfo() method from web3auth

packages/account-abstraction-kit/package.json, packages/api-kit/package.json, packages/auth-kit/package.json, packages/onramp-kit/package.json, packages/protocol-kit/package.json, packages/relay-kit/package.json, packages/safe-core-sdk-types/package.json, packages/safe-ethers-adapters/package.json
- `@safe-global/account-abstraction-kit-poc`: `v1.0.0`
- `@safe-global/api-kit`: `v1.1.0`
- `@safe-global/auth-kit`: `v1.0.0`
- `@safe-global/onramp-kit`: `v1.0.0`
- `@safe-global/protocol-kit`: `v1.0.0`
- `@safe-global/relay-kit`: `v1.0.0`
- `@safe-global/safe-core-sdk-types`: `v2.0.0`
- `@safe-global/safe-ethers-adapters`: `v0.2.0-alpha.0`
=> chore: update version numbers

packages/protocol-kit/src/Safe.ts, packages/protocol-kit/tests/e2e/createTransaction.test.ts, packages/protocol-kit/tests/e2e/offChainSignatures.test.ts
Resolves #428 
Enable `protocol-kit` to resolve owners from the config set when using predictedSafe
=> fix(protocol-kit): enable owner resolution for predicted safe

packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/src/managers/contractManager.ts, packages/protocol-kit/src/types/index.ts, packages/protocol-kit/src/utils/transactions/utils.ts, packages/protocol-kit/tests/e2e/utilsContracts.test.ts
Resolves #426
`safeDeploymentConfig` is an optional parameter in the `PredictSafeProps` type
```
export interface PredictedSafeProps {
safeAccountConfig: SafeAccountConfig
safeDeploymentConfig?: SafeDeploymentConfig
}
```
=> fix(protocol-kit): safeDeploymentConfig is an optional parameter in PredictedSafeProps

packages/account-abstraction-kit/src/AccountAbstraction.ts
Resolves:
- fix the `relayTransaction` function in the `account-abstraction-kit`
- fix the initialization of the `account-abstraction-kit` when the Safe is not deployed.
Adding a instance of the protocol kit instead of using the Safe contract instance directly.
https://github.com/safe-global/safe-core-sdk/blob/1671f01bf9dad76416bc64ed0450465a040d9c69/packages/account-abstraction-kit/src/AccountAbstraction.ts#L31-L36
=> fix(account-abstraction-kit): use the protocol kit

packages/protocol-kit/src/utils/transactions/utils.ts
Resolves #427
I should be able to create a Safe transaction even if there is not explicit Safe version in the safeSDK predict config object.
```
if (predictedSafe) {
safeVersion = predictedSafe?.safeDeploymentConfig?.safeVersion || SAFE_LAST_VERSION
```
https://github.com/safe-global/safe-core-sdk/blob/f2e8e82d88d815d7b278f605a125f4cfb2816020/packages/protocol-kit/src/utils/transactions/utils.ts#L54-L62
=> fix(protocol-kit): fix standardizeSafeTransactionData for predictedSafe flow

packages/onramp-kit/package.json
We need to consider how to deliver the packs more effectively. To quickly address this, we are removing `peerDependencies`. If the destination app is only using one pack, the execution will fail requiring other packs
=> fix(onramp-kit): Remove onramp-kit peerDeps

playground/relay-kit/paid-transaction.ts, playground/relay-kit/sponsored-transaction.ts
Updates the relay playground scripts after `gasLimit` type was changed to `string`
=> chore: fix relay playground types

README.md
The current cover image has two issues:
- Not visible when using GitHub dark mode
- Is not following the right name convention at Safe{Core}
=> chore: Update cover image

guides/integrating-the-safe-core-sdk.md, packages/account-abstraction-kit/src/AccountAbstraction.ts, packages/protocol-kit/README.md, packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/contracts/config.ts, packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/src/index.ts, packages/protocol-kit/src/managers/contractManager.ts, packages/protocol-kit/src/safeFactory/index.ts, packages/protocol-kit/src/utils/transactions/utils.ts, packages/protocol-kit/tests/e2e/core.test.ts, packages/protocol-kit/tests/e2e/safeFactory.test.ts
The SDK supports the Safe Contracts `v1.4.1`, but because they are only deployed in a couple of networks, we will still have the `v1.3.0` as default.
In case developers want to deploy `v1.4.1` Safes, they will need to [pass](https://github.com/safe-global/safe-core-sdk/tree/main/packages/protocol-kit#create) the `safeVersion` property with value `1.4.1` in the initialization of the `SafeFactory` class in the `protocol-kit`. Existing `v1.4.1` Safes are compatible by default with no specific setups.
=> Set default Safe version to 1.3.0

guides/integrating-the-safe-core-sdk.md, packages/api-kit/README.md, packages/api-kit/src/SafeApiKit.ts, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/api-kit/tests/e2e/getServiceMastercopiesInfo.test.ts, packages/api-kit/tests/endpoint/index.test.ts, packages/onramp-kit/example/client/src/components/monerium/Monerium.tsx, packages/protocol-kit/README.md, packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/adapters/ethers/contracts/SafeProxyFactory/SafeProxyFactoryEthersContract.ts, packages/protocol-kit/src/adapters/ethers/contracts/contractInstancesEthers.ts, packages/protocol-kit/src/adapters/web3/contracts/SafeProxyFactory/SafeProxyFactoryWeb3Contract.ts, packages/protocol-kit/src/adapters/web3/contracts/contractInstancesWeb3.ts, packages/protocol-kit/src/contracts/config.ts, packages/protocol-kit/src/contracts/safeDeploymentContracts.ts, packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/src/managers/contractManager.ts, packages/protocol-kit/src/safeFactory/index.ts, packages/protocol-kit/src/types/index.ts, packages/protocol-kit/src/utils/transactions/gas.ts, packages/protocol-kit/tests/e2e/contractManager.test.ts, packages/protocol-kit/tests/e2e/createSafeDeploymentTransaction.test.ts, packages/protocol-kit/tests/e2e/ethAdapters.test.ts, packages/protocol-kit/tests/e2e/safeFactory.test.ts, packages/protocol-kit/tests/e2e/utils/setupContractNetworks.ts, packages/safe-core-sdk-types/src/contracts/SafeProxyFactoryContract.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/494
- Rename `isL1SafeMasterCopy` to `isL1SafeSingleton`
```js
old: SafeFactory.create({ ethAdapter, isL1SafeMasterCopy: true })
new: SafeFactory.create({ ethAdapter, isL1SafeSingleton: true })
```
- Rename type `MasterCopyResponse` to `SafeSingletonResponse`
- Rename method `getServiceMasterCopiesInfo()` to `getServiceSingletonsInfo()`
=> refactor(protocol-kit): Rename MasterCopy to singleton

packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/tests/e2e/contractManager.test.ts, packages/protocol-kit/tests/e2e/utilsContracts.test.ts
Resolves #546 
Added `zkSyncEraCreate2Address ` that generates a zkSync Era address. zkSync Era uses a distinct address derivation method compared to Ethereum.
See: https://era.zksync.io/docs/reference/architecture/differences-with-ethereum.html#create-create2
=> Add zkSyncEraCreate2Address to generates a zkSync Era address

packages/protocol-kit/src/utils/transactions/gas.ts
Issue with the `safeTxGas` estimation.
The `parseSafeTxGasErrorResponse ` function has been enhanced to check for the existence of `Ethersv6RevertData?.originalError?.data`. If this data is present, it is now correctly used to decode the `safeTxGas`.
This issue has been found in our Demo Dapp:
=> fix: safeTxGas estimation parse for Ethers v6

packages/api-kit/package.json, packages/api-kit/tests/e2e/getServiceSingletonsInfo.test.ts
Fixes getServiceSingletons test as now the deployer can also be Safe apart from Gnosis
Check and keep Gnosis as deployer for the older versions, uses Safe for the new ones
=> fix: getServiceSingletons test

guides/integrating-the-safe-core-sdk.md, packages/api-kit/tests/endpoint/index.test.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts, packages/protocol-kit/README.md, packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/types/index.ts, packages/protocol-kit/src/utils/transactions/utils.ts, packages/protocol-kit/tests/e2e/core.test.ts, packages/protocol-kit/tests/e2e/createTransaction.test.ts, packages/protocol-kit/tests/e2e/createTransactionBatch.test.ts, packages/protocol-kit/tests/e2e/execution.test.ts, packages/protocol-kit/tests/e2e/getEncodedTransaction.test.ts, packages/protocol-kit/tests/e2e/offChainSignatures.test.ts, packages/protocol-kit/tests/e2e/onChainSignatures.test.ts, packages/protocol-kit/tests/e2e/wrapSafeTransactionIntoDeploymentBatch.test.ts, packages/relay-kit/src/packs/gelato/GelatoRelayPack.test.ts, packages/relay-kit/src/packs/gelato/GelatoRelayPack.ts, playground/api-kit/propose-transaction.ts
Resolves #334 
Create transaction accepted either an object or an array to create a new Safe transaction. This felxibility was OK, but it generates confusion and all scenarios can be covered by accepting an array only, as we also had an options object in place. Also this way, the protocol-kit create transaction aligns with the relay-kit method signature.
Accepts only an array of transactions, even if it only contains one transaction.
=> fix: createTransaction to accept only transactions array

packages/account-abstraction-kit/src/AccountAbstraction.test.ts
Setup `Safe.create` mock before initializing the AccountAbstraction instance
Resolves #593
The unit test was failing because the `Safe.create` mock had been defined only after creating the `AccountAbstraction` instance, resulting in its `protocolKit` property being undefined when running the test.
=> fix(account-abstraction-kit): getNonce unit test

packages/onramp-kit/src/lib/errors.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.test.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts
Improve exception handling in signature decoding for Monerium.pack
Added a couple of unit tests
Now we are using `Promise.allSettled` instead of `Promise.all`
Added `parseIsValidSignatureErrorResponse` and `decodeSignatureData` to parse the error
=> fix exception handling in signature decoding for Monerium Pack

packages/auth-kit/src/AuthKitBasePack.ts
This prevents an error being thrown for chains to which the TX service is not available (like Mumbai). The auth-kit should still be usable for those chains.
=> fix(auth-kit): wrap ApiKit instance creation with a try..catch

packages/safe-core-sdk-types/src/types.ts
The `proposer` field is missing from the typescript definition but returned by the Safe API.
Add the missing field in the type.
=> feat: add missing `proposer` field to `SafeMultisigTransactionWithTransfersResponse`

packages/onramp-kit/example/client/package.json, packages/onramp-kit/example/client/yarn.lock, packages/onramp-kit/package.json, packages/onramp-kit/src/packs/monerium/MoneriumPack.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.test.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts, yarn.lock
v2.9.0 of monerium/sdk now accepts chainId
=> fix(onramp-kit): monerium/sdk now accepts chainId

packages/onramp-kit/example/client/src/components/monerium/Monerium.tsx, packages/onramp-kit/src/packs/monerium/MoneriumPack.test.ts, packages/onramp-kit/src/packs/monerium/MoneriumPack.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.test.ts, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts, packages/onramp-kit/src/packs/monerium/types.ts
Rename the old safeSdk name to protocolKit so it follows the new naming convention.
=> chore: Rename protocol-kit in onramp-kit

packages/protocol-kit/package.json, packages/safe-core-sdk-types/package.json, yarn.lock
Bump `safe-deployments` to latest version to add v1.3.0 contract addreses for Base Sepolia
=> chore: bump safe deployments to add base sepolia compatibility

packages/api-kit/hardhat.config.ts, packages/api-kit/scripts/generateTxServiceTypes.sh, packages/api-kit/src/utils/config.ts, packages/api-kit/tests/endpoint/index.test.ts, packages/api-kit/tests/utils/config.ts, packages/auth-kit/example/src/App.tsx, packages/onramp-kit/example/client/src/AuthContext.tsx, packages/protocol-kit/hardhat.config.ts, playground/api-kit/confirm-transaction.ts, playground/api-kit/execute-transaction.ts, playground/api-kit/propose-transaction.ts, playground/protocol-kit/deploy-safe.ts
Resolves #729 
Add ZkSync and ZkEvm to the default `api-kit` configuration.
Also removed goerli from the default configuration, as is not supported anymore. Added few changes in the tests to avoid complaining because Goerli service is not available. 
Tests are pending to be fully migrated to Sepolia yet.
=> feat(api-kit): add ZkSync and ZkEvm service links

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, playground/relay-kit/usdc-transfer-4337-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20.ts, playground/relay-kit/usdc-transfer-4337-sponsored-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-sponsored.ts, playground/relay-kit/usdc-transfer-4337.ts
Resolves #720 
- The Safe uses v1.4.1 version.
- Safe has the 4337 module enabled.
- Safe has the 4337 fallback handler enabled.
```typescript
// 1) Initialize pack with the Safe Address
const safe4337Pack = await Safe4337Pack.init({
ethersAdapter,
rpcUrl: RPC_URL,
bundlerUrl: BUNDLER_URL,
options: {
safeAddress
}
})
```
You can use this Safes in `Sepolia` to test this checks:
- [`0x9534Bc54EB95975DaF2Dbc74ff945f0DB9810043`](https://app.safe.global/settings/setup?safe=sep:0x9534Bc54EB95975DaF2Dbc74ff945f0DB9810043): Safe with `1.3.0` version, this version is not compatible with 4337.
- [`0xfC82a1e4A045a44527e8b45FC70332C8F66fc32B`](https://app.safe.global/settings/setup?safe=sep:0xfC82a1e4A045a44527e8b45FC70332C8F66fc32B): Safe with `1.4.1` version but no 4337 Module attached.
- …
=> check if the Safe Account is 4337 compatible

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/types.ts
- Make the `sendUserOperation()` method private as `executeTransaction()` basically calls it so they are pretty similar
- Rename `paymasterOptions` to `PaymasterOptions`
=> chore(relay-kit): Make `sendUserOperation()` private

packages/auth-kit/example/package.json, packages/auth-kit/example/src/App.tsx, packages/auth-kit/example/yarn.lock, packages/onramp-kit/example/client/package.json, packages/onramp-kit/example/client/yarn.lock, packages/onramp-kit/example/server/package.json, packages/onramp-kit/example/server/yarn.lock, packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.test.ts, playground/protocol-kit/generate-safe-address.ts
bump example dependencies that generate security alerts
Bump all dependencies specially those in outdated versions
=> chore: bump example dependencies

.github/workflows/cla.yml, packages/api-kit/tests/e2e/addMessage.test.ts, packages/api-kit/tests/e2e/addMessageSignature.test.ts, packages/api-kit/tests/e2e/addSafeDelegate.test.ts, packages/api-kit/tests/e2e/confirmTransaction.test.ts, packages/api-kit/tests/e2e/decodeData.test.ts, packages/api-kit/tests/e2e/getIncomingTransactions.test.ts, packages/api-kit/tests/e2e/getMessage.test.ts, packages/api-kit/tests/e2e/getMessages.test.ts, packages/api-kit/tests/e2e/getMultisigTransactions.test.ts, packages/api-kit/tests/e2e/getNextNonce.test.ts, packages/api-kit/tests/e2e/getPendingTransactions.test.ts, packages/api-kit/tests/e2e/getSafeDelegates.test.ts, packages/api-kit/tests/e2e/getSafeInfo.test.ts, packages/api-kit/tests/e2e/getSafesByModule.test.ts, packages/api-kit/tests/e2e/getSafesByOwner.test.ts, packages/api-kit/tests/e2e/getServiceInfo.test.ts, packages/api-kit/tests/e2e/getServiceSingletonsInfo.test.ts, packages/api-kit/tests/e2e/getToken.test.ts, packages/api-kit/tests/e2e/getTokenList.test.ts, packages/api-kit/tests/e2e/getTransaction.test.ts, packages/api-kit/tests/e2e/getTransactionConfirmations.test.ts, packages/api-kit/tests/e2e/removeSafeDelegate.test.ts, packages/api-kit/tests/endpoint/index.test.ts
Resolves #687
Enable the previously failing tests and uses applicable data to Sepolia
=> Fix: migrate api kit tests to sepolia

playground/config/run.ts, playground/protocol-kit/create-execute-transaction.ts
Adds a playground script to create, sign and execute a transaction with an existing 1/1 Safe.
The script was used to verify the behavior of `createTransaction` (#110) when being called with a non-executable transaction (insufficient funds in the Safe):
| Safe version | Behavior of `createTransaction` for non-executable Tx |
|--------------|-------------------------------------------------------|
| v1.0.0       | Throws: "insufficient funds"                          |
| v1.1.1       | Throws: "insufficient funds"                          |
| v1.2.0       | Throws: "insufficient funds"                          |
| v1.3.0       | Succeeds                                              |
| v1.4.1       | Succeeds                                              |
=> Playground-create-execute-transaction

packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/SafeContractEthers.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/v1.0.0/SafeContract_V1_0_0_Ethers.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/v1.1.1/SafeContract_V1_1_1_Ethers.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/v1.2.0/SafeContract_V1_2_0_Ethers.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/v1.3.0/SafeContract_V1_3_0_Ethers.ts, packages/protocol-kit/src/adapters/ethers/contracts/Safe/v1.4.1/SafeContract_V1_4_1_Ethers.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/SafeContractWeb3.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/v1.0.0/SafeContract_V1_0_0_Web3.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/v1.1.1/SafeContract_V1_1_1_Web3.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/v1.2.0/SafeContract_V1_2_0_Web3.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/v1.3.0/SafeContract_V1_3_0_Web3.ts, packages/protocol-kit/src/adapters/web3/contracts/Safe/v1.4.1/SafeContract_V1_4_1_Web3.ts, packages/protocol-kit/src/managers/moduleManager.ts, packages/protocol-kit/tests/e2e/moduleManager.test.ts, packages/safe-core-sdk-types/src/contracts/SafeContract.ts
Resolves #607
`getModules` returns a fixed number of Modules that would potentialy truncate the output list of addresses.
Add `getModulesPaginated` from smart contract to versions that support it.
Add a function that uses `getModules` in the background for those contract versions that don't support it.
=> Feat/protocol kit/get modules paginated

packages/protocol-kit/README.md
There is a mistake in the README of the Safe protocol-kit where the args for `createTransaction` specifies a `callsOnly` param - while it should be`onlyCalls`.
You can see the [types](https://github.com/safe-global/safe-core-sdk/blob/0bc0515d4265ef099085644791d4fa1fe4e1cf55/packages/protocol-kit/src/types/index.ts#L136) here 
This PR corrects the error in the README.
Also related : https://github.com/safe-global/safe-docs/pull/459
=> replace `callsOnly` by`onlyCalls` in README

packages/protocol-kit/hardhat/deploy/deploy-contracts.ts, packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/contracts/Safe/v1.0.0/SafeContract_v1_0_0.ts, packages/protocol-kit/src/managers/moduleManager.ts, packages/protocol-kit/src/types/safeProvider.ts, packages/protocol-kit/src/utils/address.ts, packages/protocol-kit/tests/e2e/execution.test.ts, packages/protocol-kit/tests/e2e/moduleManager.test.ts, packages/protocol-kit/tests/e2e/utils/setupContracts.ts
The method `getModulesPaginated` should return a tuple containing both the modules as well as the next address of the page.
- It changes the interface by adding the missing property as a "complex type".
- It adds the type since that is the result of the interface
- It adds assertions to test that scenario
=> fix(protocol kit): Get modules paginated incorrect interface

packages/protocol-kit/package.json, packages/safe-core-sdk-types/package.json
This PR moves `abitype` to the `dependencies` in the `package.json` files
=> fix: `abitype` is not a dev dependency

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts
We have a bug in the `getEstimateFee` calculation
=> fix(relay-kit): User Operation gas estimation ignored

packages/auth-kit/package.json, packages/auth-kit/src/packs/safe-auth/SafeAuthPack.test.ts, yarn.lock
Resolves https://github.com/safe-global/safe-core-sdk/issues/826
We change the package util for mocks
=> chore(auth-kit): Remove `eth-testing` package from auth-kit

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/api-kit/tests/e2e/getSafeOperationsByAddress.test.ts, packages/api-kit/tests/endpoint/index.test.ts
`callDataGasLimit` is a non-standard prop so we are renaming it to `callGasLimit`
Related tx Service change => https://github.com/safe-global/safe-transaction-service/pull/2058
=> fix(api-kit): Rename `callDataGasLimit` to `callGasLimit`

packages/protocol-kit/package.json
Contract ABIs moved to `safe-core-sdk-types` so the protocol-kit now uses the types lib as a dependency and not only devDependency
Set `safe-core-sdk-types` as a dependency
=> fix(protocol-kit): move safe-core-sdk-types from devDependencies to dependencies

packages/relay-kit/package.json, yarn.lock
bump safe-modules-deployments to 2.1.1 version in the relay-kit to include `BASE` chain  `safe4337ModuleAddress` &  `addModulesLibAddress` contract addresses
=> chore(relay-kit): bump safe-modules-deployments to 2.1.1 version

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/api-kit/src/utils/safeOperation.ts, packages/api-kit/tests/e2e/addSafeOperation.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/SafeOperation.test.ts, packages/relay-kit/src/packs/safe-4337/SafeOperation.ts, packages/relay-kit/src/packs/safe-4337/testing-utils/fixtures.ts, packages/relay-kit/src/packs/safe-4337/types.ts, packages/relay-kit/src/packs/safe-4337/utils.ts, packages/safe-core-sdk-types/src/types.ts, playground/config/run.ts, playground/relay-kit/api-kit-interoperability.ts, playground/relay-kit/usdc-transfer-4337-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-erc20.ts, playground/relay-kit/usdc-transfer-4337-sponsored-counterfactual.ts, playground/relay-kit/usdc-transfer-4337-sponsored.ts, playground/relay-kit/usdc-transfer-4337.ts, playground/tsconfig.json, playground/utils.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/825
We are adding support for using SafeOperation responses from the transaction service in the `Safe4337Pack`
=> feat(relay-kit): Add tx service compatibility to `Safe4337Pack`

packages/protocol-kit/tests/e2e/execution.test.ts
The execution tests were failing randomly caused by a race condition.
Also found that some tests were not being executed with Viem, and that didn't make sense any more to execute separately for web3 and ethers.
Adds a small timeout to avoid the race condition.
Remove the itif filtering by provider.
=> fix(protocol-kit):  fix execution test

packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/utils.ts
Resolves #849 
Passkeys + 4337 gas estimation is not working as expected when using sponsored transactions. We add a dummy passkey signature to get a valid `verificationGasLimit` estimation.
We assume that all owners are passkeys.
=> feat(relay-kit): add dummy signature as a passkey signature

packages/api-kit/src/utils/signDelegate.ts
The API team changed the EIP-712 type for the delegate address int his PR https://github.com/safe-global/safe-transaction-service/pull/2089/files
Update the delegate address type in the signDelegate message.
=> fix(api-kit): update delegate address type

packages/api-kit/tests/e2e/confirmTransaction.test.ts, packages/api-kit/tests/e2e/getMultisigTransactions.test.ts, packages/api-kit/tests/e2e/getPendingTransactions.test.ts
Fixes the confirmTransaction test which is currently sometimes running into timeouts on the viem migration branch (#887), due to uncaught errors from `isValidSignature` requests.
The test was incorrect because it used the same transaction hash repeatedly, leading to assertions being made on an already confirmed transaction instead of a newly proposed one. By adding a timestamp to the transaction data, we ensure that each transaction hash is unique and that a new transaction is proposed for every test run.
Additionally, the test incorrectly called the `isValidSignature` function with a transaction hash. This function is intended only for messages, causing the contract call to fail consistently. However, the error was not properly caught; the function merely returns `false` when an error …
=> fix(api-kit): Fix e2e tests for multisig transactions

packages/protocol-kit/src/Safe.ts, packages/sdk-starter-kit/src/BaseClient.ts, packages/sdk-starter-kit/src/SafeClient.ts, packages/sdk-starter-kit/src/types.ts, playground/config/run.ts, playground/sdk-starter-kit/owner-management.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/940
Creating a BaseClient class with some core functionality as the owner management methods. We added as well some important ones as getSafeAddress or isSafeDeployed
=> feat(sdk-starter-kit): Add owner management methods

packages/protocol-kit/src/SafeProvider.ts
The `staticNetwork` in the JSON provider options reduces the number of RPC requests made to detect the current chain (as a Safe Account always exists on just one chain).
See https://docs.ethers.org/v6/api/providers/jsonrpc/#JsonRpcApiProviderOptions
=> Refactor: static network in JsonRpcProvider

packages/sdk-starter-kit/src/SafeClient.ts, packages/sdk-starter-kit/src/index.test.ts, packages/sdk-starter-kit/src/types.ts
This PR adds several improvements to the `sdk-starter-kit`.
- Make the `signer` parameter optional, as sometimes you may want to use the SafeClient in read-only mode. This is the same behavior that we have at the [protocol-kit level](https://github.com/safe-global/safe-core-sdk/blob/4f4e4f87e894f086a36b6ed3e15182f77633e74b/packages/protocol-kit/src/types/safeConfig.ts#L43)
- The `extend` method's definition has been updated to allow nested extends. Previously, the last `extend` call would override the previous ones in the type system, leading to some errors reported by the TypeScript compiler.
=> feat(sdk-starter-kit): Improvements

packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/contracts/BaseContract.ts, packages/protocol-kit/src/contracts/Safe/SafeBaseContract.ts, packages/protocol-kit/src/contracts/Safe/v1.0.0/SafeContract_v1_0_0.ts, packages/protocol-kit/src/contracts/Safe/v1.1.1/SafeContract_v1_1_1.ts, packages/protocol-kit/src/contracts/Safe/v1.2.0/SafeContract_v1_2_0.ts, packages/protocol-kit/src/contracts/Safe/v1.3.0/SafeContract_v1_3_0.ts, packages/protocol-kit/src/contracts/Safe/v1.4.1/SafeContract_v1_4_1.ts, packages/protocol-kit/src/contracts/config.ts, packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/src/types/safeProvider.ts, playground/config/run.ts, playground/protocol-kit/replicate-address.ts
Resolves #929
Some developers would like to deploy the same Safe address into different chains when using the SDK. While this is possible is not the default behavior of the SDK, and it's also not clear that the SDK is able to manage this situation too.
- Created a `replicate-address` playground showing this specific example.
- Fixed a bug in the `Safe.getAddress()` method (added `isL1SafeSingleton` param to `predictSafeAddress`)
- if a custom `deploymentType` is set and the address is not present in `safe-deployments` we throw an error in the `BaseContract`.
- Fix issue in `createSafeDeploymentTransaction` (added `deploymentType` param)
I used the `generate-safe-address`playground to get a Safe address starting with `0x5afe...` pattern:
- Safe Address: …
=> fix(protocol-kit): fixed `isL1SafeSingleton` issues and added the `replicate-address` playground

packages/protocol-kit/package.json, yarn.lock
Over at Zodiac Pilot, we've had some trouble with the `protocol-kit` package, as it ships only as CJS. We're upgrading our codebase to the ESM future. 
This PR splits up the build for the `protocol-kit` package to create ESM and CJS sources. I've also extended the `package.json` to conform to everything from bundlers to Node JS native module resolution. 
You'll notice that I've removed a call to `tsc-alias`. AFAICT, the sources are bundled, which means any aliases have already been resolved. Please correct me if this assumption is wrong. I've tested this locally with our extension, and it works like a charm. We're now picking up the ESM build, and everything works as expected.
Let me know if anything is missing, if you need further clarification, or if anything else comes up!
=> chore: build protocol-kit with cjs and esm targets

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/tests/e2e/decodeData.test.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/1046
Adding the `to` parameter to the `decodeData` method
=> fix(api-kit): Missing `to` parameter

guides/integrating-the-safe-core-sdk.md, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/protocol-kit/tests/e2e/offChainSignatures.test.ts, packages/relay-kit/src/packs/safe-4337/testing-utils/fixtures.ts, packages/types-kit/src/types.ts
based on this suggestion: https://github.com/safe-global/safe-core-sdk/pull/1043
```typescript
export const SignatureTypes = {
CONTRACT_SIGNATURE: 'CONTRACT_SIGNATURE',
EOA: 'EOA',
APPROVED_HASH: 'APPROVED_HASH',
ETH_SIGN: 'ETH_SIGN'
} as const
export type SignatureType = (typeof SignatureTypes)[keyof typeof SignatureTypes]
```
=> feat: add SignatureType type

packages/protocol-kit/src/types/safeProvider.ts, packages/sdk-starter-kit/src/BaseClient.ts
Missing passkey types to create transactions
=> fix(sdk-starter-kit): Add passkey types to starter

packages/protocol-kit/src/utils/passkeys/PasskeyClient.ts
Some non-standards compliant password managers (including Bitwarden) provide the passkey signature as a Uint8Array or as an Array of numbers instead of an ArrayBuffer.
This causes a "First argument to DataView constructor must be an ArrayBuffer" error in extractSignature.
This change makes this code robust to such password managers.
Solves #1054
=> fix(protocol-kit): Fix non-ArrayBuffer passkey signature error (#1054)

CONTRIBUTING.md, playground/README.md
Fixes some typos notified in #1089, #1090, #1091, and #1092
=> chore: Fix typos

packages/protocol-kit/package.json, packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/utils/getProtocolKitVersion.ts, packages/protocol-kit/tests/e2e/onChainIdentifier.test.ts, packages/protocol-kit/tsconfig.build.json, packages/protocol-kit/tsconfig.json, packages/relay-kit/package.json, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts, packages/relay-kit/src/packs/safe-4337/utils/getRelayKitVersion.ts, packages/relay-kit/tsconfig.build.json, packages/relay-kit/tsconfig.json
Generate `getProtocolKitVersion` dynamically via `prebuild` script
Updated Packages: `protocol-kit` and `realy-kit`
```
"prebuild": "node -p \"'export const getProtocolKitVersion = () => \\'' + require('./package.json').version.split('-')[0] + '\\''\" > src/utils/getProtocolKitVersion.ts",
```
this generates a `getProtocolKitVersion.ts` in the utils folder:
```typescript
export const getProtocolKitVersion = () => '5.1.1'
```
Based on: https://github.com/safe-global/safe-apps-sdk/pull/512/files#diff-5f74fd08745aa25ded644cd9a4eff498e167ba539e633f87b200cd40e4113e06R23
=> fix: Generate `getProtocolKitVersion` dynamically via `prebuild` script

packages/relay-kit/src/packs/safe-4337/utils.ts
fix `userOperationToHexValues` `nonce` encode
``` typescript
nonce: toHex(BigInt(userOperation.nonce)),
```
=> fix(relay-kit): `userOperationToHexValues` `nonce` encode

packages/types-kit/src/types.ts
Resolves #1008 
Adds that some properties could be returned as null
=> fix(types-kit): sync SafeMultisigTransactionResponse types with API

packages/api-kit/src/SafeApiKit.ts, packages/api-kit/src/types/safeTransactionServiceTypes.ts, packages/api-kit/tests/e2e/getPendingSafeOperations.test.ts, packages/api-kit/tests/e2e/getSafeOperationsByAddress.test.ts, packages/sdk-starter-kit/src/extensions/safe-operations/SafeOperationClient.test.ts, packages/sdk-starter-kit/src/extensions/safe-operations/SafeOperationClient.ts
Resolves https://github.com/safe-global/safe-core-sdk/issues/1050
- `api-kit`: Implement the endpoint with a new method.
- `sdk-starter-kit`: Use the new method in getPendingSafeOperations.
=> feat: Get pending SafeOperations support

packages/sdk-starter-kit/src/constants.ts, packages/sdk-starter-kit/src/extensions/safe-operations/safeOperations.ts
We make default the `v0.3.0` os the Safe Modules in the `relay-kit` so as `sdk-starter-kit` is not compatible until the backend services are updated then we need to default this kit to `v0.2.0`
=> fix(sdk-starter-kit): Add correct `safeModulesVersion`

packages/api-kit/src/utils/httpRequests.ts
The dual compilation breaks node-fetch in browser environments
We are importing dynamically `node-fetch` only for node environments and keep the regular `fetch` for browser
Alternatively we could upgrade to `node-fetch` 3 but is only compatible with ESM so we need to include some polyfills to avoid host apps to break
=> fix(api-kit): `node-fetch` dual compilation

packages/api-kit/tests/e2e/addSafeOperation.test.ts, packages/api-kit/tests/e2e/confirmSafeOperation.test.ts, packages/relay-kit/src/packs/safe-4337/Safe4337Pack.test.ts, packages/relay-kit/src/packs/safe-4337/constants.ts, playground/relay-kit/userop-api-kit-interoperability.ts
We are setting the default version of the safe modules for 4337 to 0.2.0 to prevent confusion for users of the `api-kit` as our backend services do not yet support the latest entry point version. Once the backend services are ready, we will revert to version 0.3.0
=> feat(relay-kit): Set default module version to 0.2.0

packages/api-kit/tests/e2e/getMultisigTransactions.test.ts, packages/api-kit/tests/e2e/getPendingTransactions.test.ts, packages/api-kit/tests/e2e/getTransaction.test.ts, packages/api-kit/tests/e2e/getTransactionConfirmations.test.ts, packages/api-kit/tests/helpers/safe.ts
The transaction queues were removed so we need to create new test cases for some failing tests
=> fix(api-kit): Tests

packages/protocol-kit/src/Safe.ts, packages/protocol-kit/src/utils/transactions/utils.ts, packages/protocol-kit/tests/e2e/createTransaction.test.ts, packages/protocol-kit/tests/e2e/passkey.test.ts
Resolves #1168 and #803
Sets MultiSendCallOnly as default multisend operation
=> feat(protocol-kit): set MultiSendCallOnly by default for MultiSend transactions

packages/protocol-kit/scripts/safe-deployments/updateLocalNetworks.ts, packages/protocol-kit/src/utils/eip-3770/config.ts
Resolves #1189
Check that node `process` exists before trying to fetch environment parameter
=> fix: check node process in config is available

packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/tests/e2e/utilsContracts.test.ts
Resolves #1195
- Adds bytecodeHash for Safes v1.4.1
- Adds Lens to the list of zkSync chains
=> fix: zksync lens predict address

.github/workflows/create-integrity-file.yml, .gitignore, package.json, packages/api-kit/package.json, packages/api-kit/tests/e2e/getMultisigTransactions.test.ts, packages/api-kit/tests/e2e/getPendingTransactions.test.ts, packages/api-kit/tests/e2e/getTransaction.test.ts, packages/api-kit/tests/e2e/getTransactionConfirmations.test.ts, packages/api-kit/tests/helpers/safe.ts, packages/protocol-kit/package.json, packages/protocol-kit/scripts/safe-deployments/updateLocalNetworks.ts, packages/protocol-kit/src/contracts/utils.ts, packages/protocol-kit/src/types/contracts.ts, packages/protocol-kit/src/utils/eip-3770/config.ts, packages/protocol-kit/src/utils/getProtocolKitVersion.ts, packages/protocol-kit/tests/e2e/utils/setupProvider.ts, packages/protocol-kit/tests/e2e/utilsContracts.test.ts, packages/relay-kit/package.json, packages/sdk-starter-kit/package.json, packages/testing-kit/package.json, packages/testing-kit/src/utils/setupContractNetworks.ts, packages/types-kit/package.json, packages/types-kit/src/contracts/assets/SafeWebAuthnSignerFactory/v0.2.1/safe_webauthn_signer_factory.ts, playground/tsconfig.json, scripts/generate-publish-info.ts, yarn.lock
Adds Lens compatibility to protocol-kit v5
Adds fix for exclude `process.env` when running in browser
Update test RPC provider
=> Bump v5 lts

packages/relay-kit/package.json
Resolves #1201 
Fix file extension for `main` and `module`
=> fix: relay-kit main and module routes

packages/api-kit/package.json, packages/relay-kit/package.json, packages/relay-kit/src/packs/safe-4337/utils/getRelayKitVersion.ts, packages/sdk-starter-kit/package.json
```
@safe-global/relay-kit: 4.0.2
@safe-global/sdk-starter-kit: 2.0.2
```
- #1201
=> Prepare release

packages/protocol-kit/package.json, packages/relay-kit/package.json, yarn.lock
Bump `@safe-global/safe-modules-deployments` to the latest version
=> chore: bump @safe-global/safe-modules-deployments

packages/api-kit/src/utils/config.ts
When initializing safe api key with Sonic chainId `46` without specifying the `txServiceUrl` 
```js
new SafeApiKit({
chainId: 46n,
// txServiceUrl: 'https://safe-transaction-sonic.safe.global/api'
})
```
The error `TypeError: There is no transaction service available for chainId 46. Please set the txServiceUrl property to use a custom transaction service.` is thrown
By adding the Sonic tx service url to the `TRANSACTION_SERVICE_URLS` dict
=> feat(api-kit): add sonic transaction service url

packages/api-kit/package.json, packages/protocol-kit/package.json, packages/protocol-kit/src/utils/eip-3770/config.ts, packages/protocol-kit/src/utils/getProtocolKitVersion.ts, packages/relay-kit/package.json, packages/sdk-starter-kit/package.json, yarn.lock
Bump Safe deployments to the latest version
=> chore: V5 lts bump safe deployments
